--------------------------------------------------------
--  File creato - giovedì-giugno-18-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DEBITO
--------------------------------------------------------

  CREATE TABLE "OOBD16"."DEBITO" 
   (	"IDDEBITO" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"IMPORTO" NUMBER(8,3), 
	"SALDATO" NUMBER(1,0) DEFAULT 0, 
	"IDSPESA" NUMBER(*,0), 
	"EMAILUTENTE" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table GRUPPO
--------------------------------------------------------

  CREATE TABLE "OOBD16"."GRUPPO" 
   (	"IDGRUPPO" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOME" VARCHAR2(30 BYTE), 
	"TIPO" VARCHAR2(15 BYTE), 
	"DATAINIZIO" DATE, 
	"DATAFINE" DATE, 
	"DESTINAZIONE" VARCHAR2(30 BYTE), 
	"NOMEESAME" VARCHAR2(30 BYTE), 
	"DATAAPPELLO" DATE, 
	"INDIRIZZO" NUMBER(*,0), 
	"EMAILPROPRIETARIO" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table INDIRIZZO
--------------------------------------------------------

  CREATE TABLE "OOBD16"."INDIRIZZO" 
   (	"IDINDIRIZZO" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"PROVINCIA" VARCHAR2(2 BYTE), 
	"CITTA" VARCHAR2(40 BYTE), 
	"VIA" VARCHAR2(40 BYTE), 
	"NUMCIVICO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table NOTIFICA
--------------------------------------------------------

  CREATE TABLE "OOBD16"."NOTIFICA" 
   (	"IDNOTIFICA" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"DATA1" DATE, 
	"DESCRIZIONE1" VARCHAR2(300 BYTE), 
	"DATARISPOSTA" DATE, 
	"DESCRIZIONERISPOSTA" VARCHAR2(300 BYTE), 
	"IDDEBITO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PARTECIPAZIONEGRUPPO
--------------------------------------------------------

  CREATE TABLE "OOBD16"."PARTECIPAZIONEGRUPPO" 
   (	"IDPARTECIPAZIONE" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"DATAINVITO" DATE DEFAULT null, 
	"STATOINVITO" NUMBER(1,0), 
	"EMAILUTENTE" VARCHAR2(40 BYTE), 
	"IDGRUPPO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SCADENZA
--------------------------------------------------------

  CREATE TABLE "OOBD16"."SCADENZA" 
   (	"IDSCADENZA" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOMESCADENZA" VARCHAR2(30 BYTE), 
	"DATA" DATE, 
	"IMPORTO" NUMBER(8,3), 
	"IDGRUPPO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SPESA
--------------------------------------------------------

  CREATE TABLE "OOBD16"."SPESA" 
   (	"IDSPESA" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOMESPESA" VARCHAR2(25 BYTE), 
	"DESCRIZIONE" VARCHAR2(300 BYTE), 
	"DATA" DATE, 
	"IMPORTO" NUMBER(8,3), 
	"ISCOMUNE" NUMBER(1,0), 
	"IDGRUPPO" NUMBER(*,0), 
	"EMAILUTENTE" VARCHAR2(40 BYTE), 
	"VALUTA" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table UTENTE
--------------------------------------------------------

  CREATE TABLE "OOBD16"."UTENTE" 
   (	"EMAILISTITUZIONALE" VARCHAR2(40 BYTE), 
	"NOME" VARCHAR2(20 BYTE), 
	"COGNOME" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"TELEFONO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table VALUTA
--------------------------------------------------------

  CREATE TABLE "OOBD16"."VALUTA" 
   (	"NOME" VARCHAR2(20 BYTE), 
	"CONVERSIONEEURO" NUMBER(8,3)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into OOBD16.DEBITO
SET DEFINE OFF;
Insert into OOBD16.DEBITO (IDDEBITO,IMPORTO,SALDATO,IDSPESA,EMAILUTENTE) values ('2','60','0','2','elena.greco@unina.it');
Insert into OOBD16.DEBITO (IDDEBITO,IMPORTO,SALDATO,IDSPESA,EMAILUTENTE) values ('3','7,9','0','3','mario.rossi@studenti.unina.it');
Insert into OOBD16.DEBITO (IDDEBITO,IMPORTO,SALDATO,IDSPESA,EMAILUTENTE) values ('4','17,5','0','4','luigi.bianchi@studenti.unina.it');
Insert into OOBD16.DEBITO (IDDEBITO,IMPORTO,SALDATO,IDSPESA,EMAILUTENTE) values ('5','32,5','0','5','anna.verdi@studenti.unina.it');
Insert into OOBD16.DEBITO (IDDEBITO,IMPORTO,SALDATO,IDSPESA,EMAILUTENTE) values ('6','11','0','6','francesca.neri@studenti.unina.it');
Insert into OOBD16.DEBITO (IDDEBITO,IMPORTO,SALDATO,IDSPESA,EMAILUTENTE) values ('7','9,25','0','7','antonio.bruni@studenti.unina.it');
Insert into OOBD16.DEBITO (IDDEBITO,IMPORTO,SALDATO,IDSPESA,EMAILUTENTE) values ('8','27,5','0','8','giovanni.sorrentino@studenti.unina.it');
Insert into OOBD16.DEBITO (IDDEBITO,IMPORTO,SALDATO,IDSPESA,EMAILUTENTE) values ('9','20','0','9','carmela.esposito@studenti.unina.it');
Insert into OOBD16.DEBITO (IDDEBITO,IMPORTO,SALDATO,IDSPESA,EMAILUTENTE) values ('10','45','0','10','vincenzo.romano@studenti.unina.it');
Insert into OOBD16.DEBITO (IDDEBITO,IMPORTO,SALDATO,IDSPESA,EMAILUTENTE) values ('1','22,75','0','1','giuseppe.gialli@unina.it');
REM INSERTING into OOBD16.GRUPPO
SET DEFINE OFF;
Insert into OOBD16.GRUPPO (IDGRUPPO,NOME,TIPO,DATAINIZIO,DATAFINE,DESTINAZIONE,NOMEESAME,DATAAPPELLO,INDIRIZZO,EMAILPROPRIETARIO) values ('2','Avvisi Studenti','Generale',null,null,null,null,null,null,'elena.greco@unina.it');
Insert into OOBD16.GRUPPO (IDGRUPPO,NOME,TIPO,DATAINIZIO,DATAFINE,DESTINAZIONE,NOMEESAME,DATAAPPELLO,INDIRIZZO,EMAILPROPRIETARIO) values ('3','Svago Ingegneria','Generale',null,null,null,null,null,null,'mario.rossi@studenti.unina.it');
Insert into OOBD16.GRUPPO (IDGRUPPO,NOME,TIPO,DATAINIZIO,DATAFINE,DESTINAZIONE,NOMEESAME,DATAAPPELLO,INDIRIZZO,EMAILPROPRIETARIO) values ('4','Gruppo Erasmus 2026','Generale',null,null,null,null,null,null,'luigi.bianchi@studenti.unina.it');
Insert into OOBD16.GRUPPO (IDGRUPPO,NOME,TIPO,DATAINIZIO,DATAFINE,DESTINAZIONE,NOMEESAME,DATAAPPELLO,INDIRIZZO,EMAILPROPRIETARIO) values ('5','Weekend Barcellona','Viaggio',to_date('01-LUG-26','DD-MON-RR'),to_date('05-LUG-26','DD-MON-RR'),'Barcellona',null,null,null,'anna.verdi@studenti.unina.it');
Insert into OOBD16.GRUPPO (IDGRUPPO,NOME,TIPO,DATAINIZIO,DATAFINE,DESTINAZIONE,NOMEESAME,DATAAPPELLO,INDIRIZZO,EMAILPROPRIETARIO) values ('6','Laurea a Londra','Viaggio',to_date('10-SET-26','DD-MON-RR'),to_date('15-SET-26','DD-MON-RR'),'Londra',null,null,null,'francesca.neri@studenti.unina.it');
Insert into OOBD16.GRUPPO (IDGRUPPO,NOME,TIPO,DATAINIZIO,DATAFINE,DESTINAZIONE,NOMEESAME,DATAAPPELLO,INDIRIZZO,EMAILPROPRIETARIO) values ('7','Gita fuori porta','Viaggio',to_date('20-GIU-26','DD-MON-RR'),to_date('21-GIU-26','DD-MON-RR'),'Roma',null,null,null,'antonio.bruni@studenti.unina.it');
Insert into OOBD16.GRUPPO (IDGRUPPO,NOME,TIPO,DATAINIZIO,DATAFINE,DESTINAZIONE,NOMEESAME,DATAAPPELLO,INDIRIZZO,EMAILPROPRIETARIO) values ('8','Vacanze Post-Esami','Viaggio',to_date('01-AGO-26','DD-MON-RR'),to_date('15-AGO-26','DD-MON-RR'),'Ibiza',null,null,null,'giovanni.sorrentino@studenti.unina.it');
Insert into OOBD16.GRUPPO (IDGRUPPO,NOME,TIPO,DATAINIZIO,DATAFINE,DESTINAZIONE,NOMEESAME,DATAAPPELLO,INDIRIZZO,EMAILPROPRIETARIO) values ('9','Casa Toledo','Coinquilini',null,null,null,null,null,'1','carmela.esposito@studenti.unina.it');
Insert into OOBD16.GRUPPO (IDGRUPPO,NOME,TIPO,DATAINIZIO,DATAFINE,DESTINAZIONE,NOMEESAME,DATAAPPELLO,INDIRIZZO,EMAILPROPRIETARIO) values ('10','Appartamento Umberto','Coinquilini',null,null,null,null,null,'2','vincenzo.romano@studenti.unina.it');
Insert into OOBD16.GRUPPO (IDGRUPPO,NOME,TIPO,DATAINIZIO,DATAFINE,DESTINAZIONE,NOMEESAME,DATAAPPELLO,INDIRIZZO,EMAILPROPRIETARIO) values ('11','Fuorisede Caserta','Coinquilini',null,null,null,null,null,'3','maria.gallo@studenti.unina.it');
Insert into OOBD16.GRUPPO (IDGRUPPO,NOME,TIPO,DATAINIZIO,DATAFINE,DESTINAZIONE,NOMEESAME,DATAAPPELLO,INDIRIZZO,EMAILPROPRIETARIO) values ('12','Collegio Salerno','Coinquilini',null,null,null,null,null,'4','lucia.riccio@studenti.unina.it');
Insert into OOBD16.GRUPPO (IDGRUPPO,NOME,TIPO,DATAINIZIO,DATAFINE,DESTINAZIONE,NOMEESAME,DATAAPPELLO,INDIRIZZO,EMAILPROPRIETARIO) values ('13','Studio Basi di Dati','Studio',null,null,null,'Basi di Dati',to_date('12-LUG-26','DD-MON-RR'),null,'salvatore.marino@unina.it');
Insert into OOBD16.GRUPPO (IDGRUPPO,NOME,TIPO,DATAINIZIO,DATAFINE,DESTINAZIONE,NOMEESAME,DATAAPPELLO,INDIRIZZO,EMAILPROPRIETARIO) values ('14','Ripasso Analisi I','Studio',null,null,null,'Analisi Matematica I',to_date('30-GIU-26','DD-MON-RR'),null,'pasquale.deRosa@studenti.unina.it');
Insert into OOBD16.GRUPPO (IDGRUPPO,NOME,TIPO,DATAINIZIO,DATAFINE,DESTINAZIONE,NOMEESAME,DATAAPPELLO,INDIRIZZO,EMAILPROPRIETARIO) values ('15','Progetto Software','Studio',null,null,null,'Ingegneria del Software',to_date('20-LUG-26','DD-MON-RR'),null,'teresa.aviso@studenti.unina.it');
Insert into OOBD16.GRUPPO (IDGRUPPO,NOME,TIPO,DATAINIZIO,DATAFINE,DESTINAZIONE,NOMEESAME,DATAAPPELLO,INDIRIZZO,EMAILPROPRIETARIO) values ('1','Bacheca Informatica','Generale',null,null,null,null,null,null,'giuseppe.gialli@unina.it');
REM INSERTING into OOBD16.INDIRIZZO
SET DEFINE OFF;
Insert into OOBD16.INDIRIZZO (IDINDIRIZZO,PROVINCIA,CITTA,VIA,NUMCIVICO) values ('1','NA','Napoli','Via Toledo','10');
Insert into OOBD16.INDIRIZZO (IDINDIRIZZO,PROVINCIA,CITTA,VIA,NUMCIVICO) values ('2','NA','Napoli','Corso Umberto I','45');
Insert into OOBD16.INDIRIZZO (IDINDIRIZZO,PROVINCIA,CITTA,VIA,NUMCIVICO) values ('3','CE','Caserta','Via Roma','120');
Insert into OOBD16.INDIRIZZO (IDINDIRIZZO,PROVINCIA,CITTA,VIA,NUMCIVICO) values ('4','SA','Salerno','Corso Vittorio Emanuele','8');
Insert into OOBD16.INDIRIZZO (IDINDIRIZZO,PROVINCIA,CITTA,VIA,NUMCIVICO) values ('5','AV','Avellino','Via Matteotti','3');
Insert into OOBD16.INDIRIZZO (IDINDIRIZZO,PROVINCIA,CITTA,VIA,NUMCIVICO) values ('6','BN','Benevento','Viale Atlantici','55');
Insert into OOBD16.INDIRIZZO (IDINDIRIZZO,PROVINCIA,CITTA,VIA,NUMCIVICO) values ('7','NA','Portici','Via Università','100');
Insert into OOBD16.INDIRIZZO (IDINDIRIZZO,PROVINCIA,CITTA,VIA,NUMCIVICO) values ('8','NA','Ercolano','Via Resina','14');
Insert into OOBD16.INDIRIZZO (IDINDIRIZZO,PROVINCIA,CITTA,VIA,NUMCIVICO) values ('9','NA','Pozzuoli','Via Napoli','200');
Insert into OOBD16.INDIRIZZO (IDINDIRIZZO,PROVINCIA,CITTA,VIA,NUMCIVICO) values ('10','CE','Aversa','Via Diaz','22');
Insert into OOBD16.INDIRIZZO (IDINDIRIZZO,PROVINCIA,CITTA,VIA,NUMCIVICO) values ('11','SA','Cava de Tirreni','Corso Mazzini','5');
Insert into OOBD16.INDIRIZZO (IDINDIRIZZO,PROVINCIA,CITTA,VIA,NUMCIVICO) values ('12','NA','Torre del Greco','Via Roma','88');
Insert into OOBD16.INDIRIZZO (IDINDIRIZZO,PROVINCIA,CITTA,VIA,NUMCIVICO) values ('13','NA','Pompei','Via Plinio','1');
Insert into OOBD16.INDIRIZZO (IDINDIRIZZO,PROVINCIA,CITTA,VIA,NUMCIVICO) values ('14','CE','Santa Maria Capua Vetere','Corso Aldo Moro','34');
Insert into OOBD16.INDIRIZZO (IDINDIRIZZO,PROVINCIA,CITTA,VIA,NUMCIVICO) values ('15','SA','Battipaglia','Via Italia','77');
REM INSERTING into OOBD16.NOTIFICA
SET DEFINE OFF;
Insert into OOBD16.NOTIFICA (IDNOTIFICA,DATA1,DESCRIZIONE1,DATARISPOSTA,DESCRIZIONERISPOSTA,IDDEBITO) values ('3',to_date('11-MAG-26','DD-MON-RR'),'Richiesta saldo pizza',to_date('12-MAG-26','DD-MON-RR'),'Purtroppo pago domani','1');
Insert into OOBD16.NOTIFICA (IDNOTIFICA,DATA1,DESCRIZIONE1,DATARISPOSTA,DESCRIZIONERISPOSTA,IDDEBITO) values ('4',to_date('11-MAG-26','DD-MON-RR'),'Richiesta saldo pizza Anna',to_date('11-MAG-26','DD-MON-RR'),'Saldato con Satispay','2');
Insert into OOBD16.NOTIFICA (IDNOTIFICA,DATA1,DESCRIZIONE1,DATARISPOSTA,DESCRIZIONERISPOSTA,IDDEBITO) values ('5',to_date('13-MAG-26','DD-MON-RR'),'Sollecito quota volo ryanair',null,null,'3');
Insert into OOBD16.NOTIFICA (IDNOTIFICA,DATA1,DESCRIZIONE1,DATARISPOSTA,DESCRIZIONERISPOSTA,IDDEBITO) values ('6',to_date('16-MAG-26','DD-MON-RR'),'Quota detersivi appartamento',null,null,'4');
Insert into OOBD16.NOTIFICA (IDNOTIFICA,DATA1,DESCRIZIONE1,DATARISPOSTA,DESCRIZIONERISPOSTA,IDDEBITO) values ('7',to_date('19-MAG-26','DD-MON-RR'),'Notifica spesa Esselunga',to_date('20-MAG-26','DD-MON-RR'),'Inviato bonifico','5');
Insert into OOBD16.NOTIFICA (IDNOTIFICA,DATA1,DESCRIZIONE1,DATARISPOSTA,DESCRIZIONERISPOSTA,IDDEBITO) values ('8',to_date('03-MAG-26','DD-MON-RR'),'Quota Taxi condiviso',null,null,'6');
Insert into OOBD16.NOTIFICA (IDNOTIFICA,DATA1,DESCRIZIONE1,DATARISPOSTA,DESCRIZIONERISPOSTA,IDDEBITO) values ('9',to_date('23-MAG-26','DD-MON-RR'),'Riparazione chiave portone',null,null,'7');
Insert into OOBD16.NOTIFICA (IDNOTIFICA,DATA1,DESCRIZIONE1,DATARISPOSTA,DESCRIZIONERISPOSTA,IDDEBITO) values ('10',to_date('26-MAG-26','DD-MON-RR'),'Divisione cancelleria esame',null,null,'8');
Insert into OOBD16.NOTIFICA (IDNOTIFICA,DATA1,DESCRIZIONE1,DATARISPOSTA,DESCRIZIONERISPOSTA,IDDEBITO) values ('11',to_date('27-MAG-26','DD-MON-RR'),'Notifica pranzo studio',to_date('27-MAG-26','DD-MON-RR'),'Ok, inviati','9');
Insert into OOBD16.NOTIFICA (IDNOTIFICA,DATA1,DESCRIZIONE1,DATARISPOSTA,DESCRIZIONERISPOSTA,IDDEBITO) values ('12',to_date('15-MAG-26','DD-MON-RR'),'Spesa Navetta Transfer',null,null,'10');
REM INSERTING into OOBD16.PARTECIPAZIONEGRUPPO
SET DEFINE OFF;
Insert into OOBD16.PARTECIPAZIONEGRUPPO (IDPARTECIPAZIONE,DATAINVITO,STATOINVITO,EMAILUTENTE,IDGRUPPO) values ('2',to_date('17-GIU-26','DD-MON-RR'),'1','elena.greco@unina.it','2');
Insert into OOBD16.PARTECIPAZIONEGRUPPO (IDPARTECIPAZIONE,DATAINVITO,STATOINVITO,EMAILUTENTE,IDGRUPPO) values ('3',to_date('17-GIU-26','DD-MON-RR'),'1','mario.rossi@studenti.unina.it','3');
Insert into OOBD16.PARTECIPAZIONEGRUPPO (IDPARTECIPAZIONE,DATAINVITO,STATOINVITO,EMAILUTENTE,IDGRUPPO) values ('4',to_date('17-GIU-26','DD-MON-RR'),'1','luigi.bianchi@studenti.unina.it','4');
Insert into OOBD16.PARTECIPAZIONEGRUPPO (IDPARTECIPAZIONE,DATAINVITO,STATOINVITO,EMAILUTENTE,IDGRUPPO) values ('5',to_date('17-GIU-26','DD-MON-RR'),'1','anna.verdi@studenti.unina.it','5');
Insert into OOBD16.PARTECIPAZIONEGRUPPO (IDPARTECIPAZIONE,DATAINVITO,STATOINVITO,EMAILUTENTE,IDGRUPPO) values ('6',to_date('17-GIU-26','DD-MON-RR'),'1','francesca.neri@studenti.unina.it','6');
Insert into OOBD16.PARTECIPAZIONEGRUPPO (IDPARTECIPAZIONE,DATAINVITO,STATOINVITO,EMAILUTENTE,IDGRUPPO) values ('7',to_date('17-GIU-26','DD-MON-RR'),'1','antonio.bruni@studenti.unina.it','7');
Insert into OOBD16.PARTECIPAZIONEGRUPPO (IDPARTECIPAZIONE,DATAINVITO,STATOINVITO,EMAILUTENTE,IDGRUPPO) values ('8',to_date('17-GIU-26','DD-MON-RR'),'1','giovanni.sorrentino@studenti.unina.it','8');
Insert into OOBD16.PARTECIPAZIONEGRUPPO (IDPARTECIPAZIONE,DATAINVITO,STATOINVITO,EMAILUTENTE,IDGRUPPO) values ('9',to_date('17-GIU-26','DD-MON-RR'),'1','carmela.esposito@studenti.unina.it','9');
Insert into OOBD16.PARTECIPAZIONEGRUPPO (IDPARTECIPAZIONE,DATAINVITO,STATOINVITO,EMAILUTENTE,IDGRUPPO) values ('10',to_date('17-GIU-26','DD-MON-RR'),'1','vincenzo.romano@studenti.unina.it','10');
Insert into OOBD16.PARTECIPAZIONEGRUPPO (IDPARTECIPAZIONE,DATAINVITO,STATOINVITO,EMAILUTENTE,IDGRUPPO) values ('11',to_date('17-GIU-26','DD-MON-RR'),'1','maria.gallo@studenti.unina.it','11');
Insert into OOBD16.PARTECIPAZIONEGRUPPO (IDPARTECIPAZIONE,DATAINVITO,STATOINVITO,EMAILUTENTE,IDGRUPPO) values ('12',to_date('17-GIU-26','DD-MON-RR'),'1','lucia.riccio@studenti.unina.it','12');
Insert into OOBD16.PARTECIPAZIONEGRUPPO (IDPARTECIPAZIONE,DATAINVITO,STATOINVITO,EMAILUTENTE,IDGRUPPO) values ('13',to_date('17-GIU-26','DD-MON-RR'),'1','salvatore.marino@unina.it','13');
Insert into OOBD16.PARTECIPAZIONEGRUPPO (IDPARTECIPAZIONE,DATAINVITO,STATOINVITO,EMAILUTENTE,IDGRUPPO) values ('14',to_date('17-GIU-26','DD-MON-RR'),'1','pasquale.deRosa@studenti.unina.it','14');
Insert into OOBD16.PARTECIPAZIONEGRUPPO (IDPARTECIPAZIONE,DATAINVITO,STATOINVITO,EMAILUTENTE,IDGRUPPO) values ('15',to_date('17-GIU-26','DD-MON-RR'),'1','teresa.aviso@studenti.unina.it','15');
Insert into OOBD16.PARTECIPAZIONEGRUPPO (IDPARTECIPAZIONE,DATAINVITO,STATOINVITO,EMAILUTENTE,IDGRUPPO) values ('16',to_date('01-MAG-26','DD-MON-RR'),'1','mario.rossi@studenti.unina.it','1');
Insert into OOBD16.PARTECIPAZIONEGRUPPO (IDPARTECIPAZIONE,DATAINVITO,STATOINVITO,EMAILUTENTE,IDGRUPPO) values ('17',to_date('02-MAG-26','DD-MON-RR'),'1','luigi.bianchi@studenti.unina.it','1');
Insert into OOBD16.PARTECIPAZIONEGRUPPO (IDPARTECIPAZIONE,DATAINVITO,STATOINVITO,EMAILUTENTE,IDGRUPPO) values ('18',to_date('03-MAG-26','DD-MON-RR'),'0','anna.verdi@studenti.unina.it','1');
Insert into OOBD16.PARTECIPAZIONEGRUPPO (IDPARTECIPAZIONE,DATAINVITO,STATOINVITO,EMAILUTENTE,IDGRUPPO) values ('19',to_date('04-MAG-26','DD-MON-RR'),'1','francesca.neri@studenti.unina.it','2');
Insert into OOBD16.PARTECIPAZIONEGRUPPO (IDPARTECIPAZIONE,DATAINVITO,STATOINVITO,EMAILUTENTE,IDGRUPPO) values ('20',to_date('05-MAG-26','DD-MON-RR'),'1','antonio.bruni@studenti.unina.it','3');
Insert into OOBD16.PARTECIPAZIONEGRUPPO (IDPARTECIPAZIONE,DATAINVITO,STATOINVITO,EMAILUTENTE,IDGRUPPO) values ('21',to_date('06-MAG-26','DD-MON-RR'),'1','giovanni.sorrentino@studenti.unina.it','5');
Insert into OOBD16.PARTECIPAZIONEGRUPPO (IDPARTECIPAZIONE,DATAINVITO,STATOINVITO,EMAILUTENTE,IDGRUPPO) values ('22',to_date('07-MAG-26','DD-MON-RR'),'1','carmela.esposito@studenti.unina.it','5');
Insert into OOBD16.PARTECIPAZIONEGRUPPO (IDPARTECIPAZIONE,DATAINVITO,STATOINVITO,EMAILUTENTE,IDGRUPPO) values ('23',to_date('08-MAG-26','DD-MON-RR'),'0','vincenzo.romano@studenti.unina.it','6');
Insert into OOBD16.PARTECIPAZIONEGRUPPO (IDPARTECIPAZIONE,DATAINVITO,STATOINVITO,EMAILUTENTE,IDGRUPPO) values ('24',to_date('09-MAG-26','DD-MON-RR'),'1','maria.gallo@studenti.unina.it','9');
Insert into OOBD16.PARTECIPAZIONEGRUPPO (IDPARTECIPAZIONE,DATAINVITO,STATOINVITO,EMAILUTENTE,IDGRUPPO) values ('25',to_date('10-MAG-26','DD-MON-RR'),'1','lucia.riccio@studenti.unina.it','9');
Insert into OOBD16.PARTECIPAZIONEGRUPPO (IDPARTECIPAZIONE,DATAINVITO,STATOINVITO,EMAILUTENTE,IDGRUPPO) values ('26',to_date('11-MAG-26','DD-MON-RR'),'1','pasquale.deRosa@studenti.unina.it','10');
Insert into OOBD16.PARTECIPAZIONEGRUPPO (IDPARTECIPAZIONE,DATAINVITO,STATOINVITO,EMAILUTENTE,IDGRUPPO) values ('27',to_date('12-MAG-26','DD-MON-RR'),'1','teresa.aviso@studenti.unina.it','13');
Insert into OOBD16.PARTECIPAZIONEGRUPPO (IDPARTECIPAZIONE,DATAINVITO,STATOINVITO,EMAILUTENTE,IDGRUPPO) values ('28',to_date('13-MAG-26','DD-MON-RR'),'1','mario.rossi@studenti.unina.it','13');
Insert into OOBD16.PARTECIPAZIONEGRUPPO (IDPARTECIPAZIONE,DATAINVITO,STATOINVITO,EMAILUTENTE,IDGRUPPO) values ('29',to_date('14-MAG-26','DD-MON-RR'),'1','luigi.bianchi@studenti.unina.it','14');
Insert into OOBD16.PARTECIPAZIONEGRUPPO (IDPARTECIPAZIONE,DATAINVITO,STATOINVITO,EMAILUTENTE,IDGRUPPO) values ('30',to_date('15-MAG-26','DD-MON-RR'),'1','anna.verdi@studenti.unina.it','15');
Insert into OOBD16.PARTECIPAZIONEGRUPPO (IDPARTECIPAZIONE,DATAINVITO,STATOINVITO,EMAILUTENTE,IDGRUPPO) values ('1',to_date('17-GIU-26','DD-MON-RR'),'1','giuseppe.gialli@unina.it','1');
REM INSERTING into OOBD16.SCADENZA
SET DEFINE OFF;
Insert into OOBD16.SCADENZA (IDSCADENZA,NOMESCADENZA,DATA,IMPORTO,IDGRUPPO) values ('3','Affitto Giugno',to_date('01-GIU-26','DD-MON-RR'),'350','9');
Insert into OOBD16.SCADENZA (IDSCADENZA,NOMESCADENZA,DATA,IMPORTO,IDGRUPPO) values ('4','Bolletta Luce',to_date('15-GIU-26','DD-MON-RR'),'85,5','9');
Insert into OOBD16.SCADENZA (IDSCADENZA,NOMESCADENZA,DATA,IMPORTO,IDGRUPPO) values ('5','Internet Wifi',to_date('10-GIU-26','DD-MON-RR'),'29,9','10');
Insert into OOBD16.SCADENZA (IDSCADENZA,NOMESCADENZA,DATA,IMPORTO,IDGRUPPO) values ('6','Rata Volo Barcellona',to_date('20-GIU-26','DD-MON-RR'),'120','5');
Insert into OOBD16.SCADENZA (IDSCADENZA,NOMESCADENZA,DATA,IMPORTO,IDGRUPPO) values ('7','Caparra Hotel Londra',to_date('01-LUG-26','DD-MON-RR'),'450','6');
Insert into OOBD16.SCADENZA (IDSCADENZA,NOMESCADENZA,DATA,IMPORTO,IDGRUPPO) values ('8','Acquisto Libri Testo',to_date('05-GIU-26','DD-MON-RR'),'65','13');
Insert into OOBD16.SCADENZA (IDSCADENZA,NOMESCADENZA,DATA,IMPORTO,IDGRUPPO) values ('9','Quota Iscrizione Hackathon',to_date('18-GIU-26','DD-MON-RR'),'15','15');
Insert into OOBD16.SCADENZA (IDSCADENZA,NOMESCADENZA,DATA,IMPORTO,IDGRUPPO) values ('10','Condominio Trimestre',to_date('05-LUG-26','DD-MON-RR'),'110','11');
Insert into OOBD16.SCADENZA (IDSCADENZA,NOMESCADENZA,DATA,IMPORTO,IDGRUPPO) values ('11','Spesa Alimentare Comune',to_date('08-GIU-26','DD-MON-RR'),'45,3','9');
Insert into OOBD16.SCADENZA (IDSCADENZA,NOMESCADENZA,DATA,IMPORTO,IDGRUPPO) values ('12','Noleggio Auto Viaggio',to_date('25-LUG-26','DD-MON-RR'),'230','8');
Insert into OOBD16.SCADENZA (IDSCADENZA,NOMESCADENZA,DATA,IMPORTO,IDGRUPPO) values ('13','Biglietti Museo',to_date('02-LUG-26','DD-MON-RR'),'18,5','5');
Insert into OOBD16.SCADENZA (IDSCADENZA,NOMESCADENZA,DATA,IMPORTO,IDGRUPPO) values ('14','Bolletta Gas',to_date('28-GIU-26','DD-MON-RR'),'92,4','10');
Insert into OOBD16.SCADENZA (IDSCADENZA,NOMESCADENZA,DATA,IMPORTO,IDGRUPPO) values ('15','Materiale Progetto Corrente',to_date('12-GIU-26','DD-MON-RR'),'25','15');
Insert into OOBD16.SCADENZA (IDSCADENZA,NOMESCADENZA,DATA,IMPORTO,IDGRUPPO) values ('16','Rifornimento Benzina Gite',to_date('19-GIU-26','DD-MON-RR'),'50','7');
Insert into OOBD16.SCADENZA (IDSCADENZA,NOMESCADENZA,DATA,IMPORTO,IDGRUPPO) values ('17','Pulizie fine mese',to_date('30-GIU-26','DD-MON-RR'),'40','12');
REM INSERTING into OOBD16.SPESA
SET DEFINE OFF;
Insert into OOBD16.SPESA (IDSPESA,NOMESPESA,DESCRIZIONE,DATA,IMPORTO,ISCOMUNE,IDGRUPPO,EMAILUTENTE,VALUTA) values ('2','Alloggio Barcellona','Caparra alloggio',to_date('17-GIU-26','DD-MON-RR'),'120','1','2','elena.greco@unina.it','Euro');
Insert into OOBD16.SPESA (IDSPESA,NOMESPESA,DESCRIZIONE,DATA,IMPORTO,ISCOMUNE,IDGRUPPO,EMAILUTENTE,VALUTA) values ('3','Fotocopie Corso','Stampa slide corso',to_date('17-GIU-26','DD-MON-RR'),'15,8','1','3','mario.rossi@studenti.unina.it','Euro');
Insert into OOBD16.SPESA (IDSPESA,NOMESPESA,DESCRIZIONE,DATA,IMPORTO,ISCOMUNE,IDGRUPPO,EMAILUTENTE,VALUTA) values ('4','Regalo Compleanno','Regalo di compleanno comune',to_date('17-GIU-26','DD-MON-RR'),'35','1','4','luigi.bianchi@studenti.unina.it','Euro');
Insert into OOBD16.SPESA (IDSPESA,NOMESPESA,DESCRIZIONE,DATA,IMPORTO,ISCOMUNE,IDGRUPPO,EMAILUTENTE,VALUTA) values ('5','Spesa Alimentari','Spesa alimentari cena',to_date('17-GIU-26','DD-MON-RR'),'65','1','5','anna.verdi@studenti.unina.it','Euro');
Insert into OOBD16.SPESA (IDSPESA,NOMESPESA,DESCRIZIONE,DATA,IMPORTO,ISCOMUNE,IDGRUPPO,EMAILUTENTE,VALUTA) values ('6','Biglietti Treno','Biglietti treno fiera',to_date('17-GIU-26','DD-MON-RR'),'22','1','6','francesca.neri@studenti.unina.it','Euro');
Insert into OOBD16.SPESA (IDSPESA,NOMESPESA,DESCRIZIONE,DATA,IMPORTO,ISCOMUNE,IDGRUPPO,EMAILUTENTE,VALUTA) values ('7','Caffè Studio','Caffè e snack sessione studio',to_date('17-GIU-26','DD-MON-RR'),'18,5','1','7','antonio.bruni@studenti.unina.it','Euro');
Insert into OOBD16.SPESA (IDSPESA,NOMESPESA,DESCRIZIONE,DATA,IMPORTO,ISCOMUNE,IDGRUPPO,EMAILUTENTE,VALUTA) values ('8','Modem Wi-Fi','Ricarica giga modem',to_date('17-GIU-26','DD-MON-RR'),'55','1','8','giovanni.sorrentino@studenti.unina.it','Euro');
Insert into OOBD16.SPESA (IDSPESA,NOMESPESA,DESCRIZIONE,DATA,IMPORTO,ISCOMUNE,IDGRUPPO,EMAILUTENTE,VALUTA) values ('9','Noleggio Aula','Noleggio aula proiezione',to_date('17-GIU-26','DD-MON-RR'),'40','1','9','carmela.esposito@studenti.unina.it','Euro');
Insert into OOBD16.SPESA (IDSPESA,NOMESPESA,DESCRIZIONE,DATA,IMPORTO,ISCOMUNE,IDGRUPPO,EMAILUTENTE,VALUTA) values ('10','Campo Calcetto','Prenotazione campo',to_date('17-GIU-26','DD-MON-RR'),'90','1','10','vincenzo.romano@studenti.unina.it','Euro');
Insert into OOBD16.SPESA (IDSPESA,NOMESPESA,DESCRIZIONE,DATA,IMPORTO,ISCOMUNE,IDGRUPPO,EMAILUTENTE,VALUTA) values ('1','Libri Informatica','Acquisto libri e dispense',to_date('17-GIU-26','DD-MON-RR'),'45,5','1','1','giuseppe.gialli@unina.it','Euro');
REM INSERTING into OOBD16.UTENTE
SET DEFINE OFF;
Insert into OOBD16.UTENTE (EMAILISTITUZIONALE,NOME,COGNOME,PASSWORD,TELEFONO) values ('mario.rossi@studenti.unina.it','Mario','Rossi','Password123!','3331234567');
Insert into OOBD16.UTENTE (EMAILISTITUZIONALE,NOME,COGNOME,PASSWORD,TELEFONO) values ('luigi.bianchi@studenti.unina.it','Luigi','Bianchi','Sicura987#','3401234567');
Insert into OOBD16.UTENTE (EMAILISTITUZIONALE,NOME,COGNOME,PASSWORD,TELEFONO) values ('anna.verdi@studenti.unina.it','Anna','Verdi','Annabella1$','3281234567');
Insert into OOBD16.UTENTE (EMAILISTITUZIONALE,NOME,COGNOME,PASSWORD,TELEFONO) values ('giuseppe.gialli@unina.it','Giuseppe','Gialli','Docente2024!','3391234567');
Insert into OOBD16.UTENTE (EMAILISTITUZIONALE,NOME,COGNOME,PASSWORD,TELEFONO) values ('francesca.neri@studenti.unina.it','Francesca','Neri','CheSpettacolo1?','3351234567');
Insert into OOBD16.UTENTE (EMAILISTITUZIONALE,NOME,COGNOME,PASSWORD,TELEFONO) values ('antonio.bruni@studenti.unina.it','Antonio','Bruni','AntoBruni99@','3471234567');
Insert into OOBD16.UTENTE (EMAILISTITUZIONALE,NOME,COGNOME,PASSWORD,TELEFONO) values ('elena.greco@unina.it','Elena','Greco','Professoressa2#','3491234567');
Insert into OOBD16.UTENTE (EMAILISTITUZIONALE,NOME,COGNOME,PASSWORD,TELEFONO) values ('giovanni.sorrentino@studenti.unina.it','Giovanni','Sorrentino','Napoli2026!','3311234567');
Insert into OOBD16.UTENTE (EMAILISTITUZIONALE,NOME,COGNOME,PASSWORD,TELEFONO) values ('carmela.esposito@studenti.unina.it','Carmela','Esposito','Carme1995*','3201234567');
Insert into OOBD16.UTENTE (EMAILISTITUZIONALE,NOME,COGNOME,PASSWORD,TELEFONO) values ('vincenzo.romano@studenti.unina.it','Vincenzo','Romano','EnzoUnina22@','3271234567');
Insert into OOBD16.UTENTE (EMAILISTITUZIONALE,NOME,COGNOME,PASSWORD,TELEFONO) values ('maria.gallo@studenti.unina.it','Maria','Gallo','MeryGallo88!','3341234567');
Insert into OOBD16.UTENTE (EMAILISTITUZIONALE,NOME,COGNOME,PASSWORD,TELEFONO) values ('salvatore.marino@unina.it','Salvatore','Marino','SalvaMar123#','3661234567');
Insert into OOBD16.UTENTE (EMAILISTITUZIONALE,NOME,COGNOME,PASSWORD,TELEFONO) values ('lucia.riccio@studenti.unina.it','Lucia','Riccio','Lucietta00$','3881234567');
Insert into OOBD16.UTENTE (EMAILISTITUZIONALE,NOME,COGNOME,PASSWORD,TELEFONO) values ('pasquale.deRosa@studenti.unina.it','Pasquale','De Rosa','Pasq1991?!','3891234567');
Insert into OOBD16.UTENTE (EMAILISTITUZIONALE,NOME,COGNOME,PASSWORD,TELEFONO) values ('teresa.aviso@studenti.unina.it','Teresa','Aviso','TereAviso20*','3511234567');
REM INSERTING into OOBD16.VALUTA
SET DEFINE OFF;
Insert into OOBD16.VALUTA (NOME,CONVERSIONEEURO) values ('Euro','1');
Insert into OOBD16.VALUTA (NOME,CONVERSIONEEURO) values ('Dollaro USA','0,92');
Insert into OOBD16.VALUTA (NOME,CONVERSIONEEURO) values ('Sterlina','1,17');
Insert into OOBD16.VALUTA (NOME,CONVERSIONEEURO) values ('Yen Giapponese','0,006');
Insert into OOBD16.VALUTA (NOME,CONVERSIONEEURO) values ('Franco Svizzero','1,04');
Insert into OOBD16.VALUTA (NOME,CONVERSIONEEURO) values ('Dollaro Canadese','0,68');
Insert into OOBD16.VALUTA (NOME,CONVERSIONEEURO) values ('Dollaro Australiano','0,61');
Insert into OOBD16.VALUTA (NOME,CONVERSIONEEURO) values ('Corona Svedese','0,088');
Insert into OOBD16.VALUTA (NOME,CONVERSIONEEURO) values ('Corona Norvegese','0,086');
Insert into OOBD16.VALUTA (NOME,CONVERSIONEEURO) values ('Zloty Polacco','0,23');
Insert into OOBD16.VALUTA (NOME,CONVERSIONEEURO) values ('Rupia Indiana','0,011');
Insert into OOBD16.VALUTA (NOME,CONVERSIONEEURO) values ('Yuan Cinese','0,13');
Insert into OOBD16.VALUTA (NOME,CONVERSIONEEURO) values ('Real Brasiliano','0,18');
Insert into OOBD16.VALUTA (NOME,CONVERSIONEEURO) values ('Peso Messicano','0,054');
--------------------------------------------------------
--  DDL for Index PARTECIPAZIONEUNICA
--------------------------------------------------------

  CREATE UNIQUE INDEX "OOBD16"."PARTECIPAZIONEUNICA" ON "OOBD16"."PARTECIPAZIONEGRUPPO" ("EMAILUTENTE", "IDGRUPPO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UNIQUE_GRUPPO
--------------------------------------------------------

  CREATE UNIQUE INDEX "OOBD16"."UNIQUE_GRUPPO" ON "OOBD16"."GRUPPO" ("NOME", "TIPO", "EMAILPROPRIETARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger TRG_AUTO_MEMBRO_PROPRIETARIO
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "OOBD16"."TRG_AUTO_MEMBRO_PROPRIETARIO" 
AFTER INSERT ON Gruppo
FOR EACH ROW
BEGIN
    INSERT INTO PartecipazioneGruppo (idGruppo, emailUtente, statoInvito, DATAINVITO)
    VALUES (:NEW.idGruppo, :NEW.emailProprietario, 1, CURRENT_DATE);
END;
/
ALTER TRIGGER "OOBD16"."TRG_AUTO_MEMBRO_PROPRIETARIO" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_CONTROLLO_CAMBIO_PROPRIETARIO
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "OOBD16"."TRG_CONTROLLO_CAMBIO_PROPRIETARIO" 
BEFORE UPDATE OF emailProprietario ON Gruppo
FOR EACH ROW
DECLARE
    v_is_membro NUMBER;
BEGIN
    -- Conta se il nuovo proprietario fa già parte del gruppo con invito accettato (statoInvito = 1)
    SELECT COUNT(*)
    INTO v_is_membro
    FROM PartecipazioneGruppo
    WHERE idGruppo = :NEW.idGruppo 
      AND emailUtente = :NEW.emailProprietario
      AND statoInvito = 1;

    -- Se il conteggio è 0, blocca l'operazione
    IF v_is_membro = 0 THEN
        RAISE_APPLICATION_ERROR(
            -20002, 
            'Violazione Vincolo: Impossibile nominare ' || :NEW.emailProprietario || 
            ' come proprietario del gruppo #' || :NEW.idGruppo || 
            ' perché non è un membro attivo!'
        );
    END IF;
END;
/
ALTER TRIGGER "OOBD16"."TRG_CONTROLLO_CAMBIO_PROPRIETARIO" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_DEBITORE_NEL_GRUPPO
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "OOBD16"."TRG_DEBITORE_NEL_GRUPPO" 
BEFORE INSERT OR UPDATE OF idSpesa, emailUtente ON Debito
FOR EACH ROW
DECLARE
    v_id_gruppo_spesa INT;
    v_is_membro        NUMBER;
BEGIN
    SELECT idGruppo 
    INTO v_id_gruppo_spesa
    FROM Spesa
    WHERE idSpesa = :NEW.idSpesa;

    SELECT COUNT(*)
    INTO v_is_membro
    FROM PartecipazioneGruppo
    WHERE idGruppo = v_id_gruppo_spesa 
      AND emailUtente = :NEW.emailUtente
      AND statoInvito = 1; -- Assicuriamoci che l'utente sia attivo nel gruppo

    IF v_is_membro = 0 THEN
        RAISE_APPLICATION_ERROR(
            -20003, 
            'Violazione Vincolo: Impossibile assegnare il debito all''utente ' || :NEW.emailUtente || 
            ' per la spesa #' || :NEW.idSpesa || 
            ' perché non partecipa al gruppo di questa spesa (Gruppo #' || v_id_gruppo_spesa || ').'
        );
    END IF;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20004, 'Errore: La spesa specificata non esiste.');
END;
/
ALTER TRIGGER "OOBD16"."TRG_DEBITORE_NEL_GRUPPO" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_EFFETTUANTE_NEL_GRUPPO
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "OOBD16"."TRG_EFFETTUANTE_NEL_GRUPPO" 
BEFORE INSERT OR UPDATE OF emailUtente, idGruppo ON Spesa
FOR EACH ROW
DECLARE
    v_is_membro NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_is_membro
    FROM PartecipazioneGruppo
    WHERE idGruppo = :NEW.idGruppo 
      AND emailUtente = :NEW.emailUtente
      AND statoInvito = 1;

    IF v_is_membro = 0 THEN
        RAISE_APPLICATION_ERROR(
            -20002, 
            'Violazione Vincolo: L''utente ' || :NEW.emailUtente || 
            ' non può registrare una spesa nel gruppo #' || :NEW.idGruppo || 
            ' perché non ne è un membro!'
        );
    END IF;
END;
/
ALTER TRIGGER "OOBD16"."TRG_EFFETTUANTE_NEL_GRUPPO" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_SPESA_COMUNE_GENERA_DEBITO
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "OOBD16"."TRG_SPESA_COMUNE_GENERA_DEBITO" 
BEFORE INSERT OR UPDATE OF idSpesa ON Debito
FOR EACH ROW
DECLARE
	v_isComune_spesa NUMBER(1);
BEGIN
	SELECT isComune
	INTO v_isComune_spesa
	FROM Spesa
	WHERE idSpesa=:NEW.idSpesa;

	IF(v_isComune_spesa<>1) THEN
	RAISE_APPLICATION_ERROR(-20005, 'Violazione Vincolo: Impossibile creare un debito per la spesa #' || :NEW.idSpesa || ' perché si tratta di una spesa privata (isComune = 0).');
	END IF;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20006, 'Errore: La spesa collegata a questo debito non esiste.');
END;
/
ALTER TRIGGER "OOBD16"."TRG_SPESA_COMUNE_GENERA_DEBITO" ENABLE;
--------------------------------------------------------
--  Constraints for Table UTENTE
--------------------------------------------------------

  ALTER TABLE "OOBD16"."UTENTE" MODIFY ("NOME" NOT NULL ENABLE);
  ALTER TABLE "OOBD16"."UTENTE" MODIFY ("COGNOME" NOT NULL ENABLE);
  ALTER TABLE "OOBD16"."UTENTE" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "OOBD16"."UTENTE" ADD CONSTRAINT "D_EMAIL" CHECK (emailIstituzionale LIKE '%@studenti.unina.it' OR emailIstituzionale LIKE '%@unina.it') ENABLE;
  ALTER TABLE "OOBD16"."UTENTE" ADD CONSTRAINT "D_TELEFONO" CHECK (LENGTH(telefono)=10) ENABLE;
  ALTER TABLE "OOBD16"."UTENTE" ADD PRIMARY KEY ("EMAILISTITUZIONALE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "OOBD16"."UTENTE" ADD CONSTRAINT "D_PASSWORD" CHECK (
    LENGTH(password) >= 8 
    AND REGEXP_LIKE(password, '[A-Z]')       -- Contiene almeno una maiuscola
    AND REGEXP_LIKE(password, '[0-9]')       -- Contiene almeno un numero
    AND REGEXP_LIKE(password, '[!@#$%^&*(),.?":{}|_-]') -- Contiene almeno un carattere speciale
) ENABLE;
--------------------------------------------------------
--  Constraints for Table DEBITO
--------------------------------------------------------

  ALTER TABLE "OOBD16"."DEBITO" MODIFY ("IDDEBITO" NOT NULL ENABLE);
  ALTER TABLE "OOBD16"."DEBITO" MODIFY ("IMPORTO" NOT NULL ENABLE);
  ALTER TABLE "OOBD16"."DEBITO" MODIFY ("SALDATO" NOT NULL ENABLE);
  ALTER TABLE "OOBD16"."DEBITO" ADD CONSTRAINT "BOOL_SALDATO" CHECK (saldato IN(0,1)) ENABLE;
  ALTER TABLE "OOBD16"."DEBITO" ADD CONSTRAINT "D_IMPORTO3" CHECK (importo>0) ENABLE;
  ALTER TABLE "OOBD16"."DEBITO" ADD PRIMARY KEY ("IDDEBITO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SPESA
--------------------------------------------------------

  ALTER TABLE "OOBD16"."SPESA" MODIFY ("IDSPESA" NOT NULL ENABLE);
  ALTER TABLE "OOBD16"."SPESA" MODIFY ("NOMESPESA" NOT NULL ENABLE);
  ALTER TABLE "OOBD16"."SPESA" MODIFY ("DATA" NOT NULL ENABLE);
  ALTER TABLE "OOBD16"."SPESA" MODIFY ("IMPORTO" NOT NULL ENABLE);
  ALTER TABLE "OOBD16"."SPESA" MODIFY ("ISCOMUNE" NOT NULL ENABLE);
  ALTER TABLE "OOBD16"."SPESA" MODIFY ("IDGRUPPO" NOT NULL ENABLE);
  ALTER TABLE "OOBD16"."SPESA" MODIFY ("EMAILUTENTE" NOT NULL ENABLE);
  ALTER TABLE "OOBD16"."SPESA" MODIFY ("VALUTA" NOT NULL ENABLE);
  ALTER TABLE "OOBD16"."SPESA" ADD CONSTRAINT "BOOL_ISCOMUNE" CHECK (isComune IN(0,1)) ENABLE;
  ALTER TABLE "OOBD16"."SPESA" ADD CONSTRAINT "D_IMPORTO2" CHECK (importo>0) ENABLE;
  ALTER TABLE "OOBD16"."SPESA" ADD PRIMARY KEY ("IDSPESA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SCADENZA
--------------------------------------------------------

  ALTER TABLE "OOBD16"."SCADENZA" MODIFY ("IDSCADENZA" NOT NULL ENABLE);
  ALTER TABLE "OOBD16"."SCADENZA" MODIFY ("NOMESCADENZA" NOT NULL ENABLE);
  ALTER TABLE "OOBD16"."SCADENZA" MODIFY ("DATA" NOT NULL ENABLE);
  ALTER TABLE "OOBD16"."SCADENZA" MODIFY ("IMPORTO" NOT NULL ENABLE);
  ALTER TABLE "OOBD16"."SCADENZA" MODIFY ("IDGRUPPO" NOT NULL ENABLE);
  ALTER TABLE "OOBD16"."SCADENZA" ADD CONSTRAINT "D_IMPORTO" CHECK (importo>=0) ENABLE;
  ALTER TABLE "OOBD16"."SCADENZA" ADD PRIMARY KEY ("IDSCADENZA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table VALUTA
--------------------------------------------------------

  ALTER TABLE "OOBD16"."VALUTA" MODIFY ("CONVERSIONEEURO" NOT NULL ENABLE);
  ALTER TABLE "OOBD16"."VALUTA" ADD CONSTRAINT "D_CONVERSIONEEURO" CHECK (conversioneEuro>0) ENABLE;
  ALTER TABLE "OOBD16"."VALUTA" ADD PRIMARY KEY ("NOME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table INDIRIZZO
--------------------------------------------------------

  ALTER TABLE "OOBD16"."INDIRIZZO" ADD CONSTRAINT "PROVINCIAL" CHECK (REGEXP_LIKE(provincia, '^[A-Z]{2}$')) ENABLE;
  ALTER TABLE "OOBD16"."INDIRIZZO" MODIFY ("IDINDIRIZZO" NOT NULL ENABLE);
  ALTER TABLE "OOBD16"."INDIRIZZO" ADD PRIMARY KEY ("IDINDIRIZZO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table GRUPPO
--------------------------------------------------------

  ALTER TABLE "OOBD16"."GRUPPO" ADD CONSTRAINT "UNIQUE_GRUPPO" UNIQUE ("NOME", "TIPO", "EMAILPROPRIETARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "OOBD16"."GRUPPO" MODIFY ("IDGRUPPO" NOT NULL ENABLE);
  ALTER TABLE "OOBD16"."GRUPPO" MODIFY ("NOME" NOT NULL ENABLE);
  ALTER TABLE "OOBD16"."GRUPPO" MODIFY ("EMAILPROPRIETARIO" NOT NULL ENABLE);
  ALTER TABLE "OOBD16"."GRUPPO" ADD CONSTRAINT "ENUM_TIPO" CHECK (tipo IN('Generale','Coinquilini','Viaggio','Studio')) ENABLE;
  ALTER TABLE "OOBD16"."GRUPPO" ADD CONSTRAINT "TIPOGRUPPO" CHECK (
(tipo='Generale' AND dataInizio IS NULL AND dataFine IS NULL AND destinazione IS NULL AND nomeEsame IS NULL AND dataAppello IS NULL AND indirizzo IS NULL) OR
(tipo='Viaggio' AND dataInizio IS NOT NULL AND dataFine IS NOT NULL AND destinazione IS NOT NULL AND nomeEsame IS NULL AND dataAppello IS NULL AND indirizzo IS NULL) OR
(tipo='Coinquilini' AND dataInizio IS NULL AND dataFine IS NULL AND destinazione IS NULL AND nomeEsame IS NULL AND dataAppello IS NULL AND indirizzo IS NOT NULL) OR
(tipo='Studio' AND dataInizio IS NULL AND dataFine IS NULL AND destinazione IS NULL AND nomeEsame IS NOT NULL AND dataAppello IS NOT NULL AND indirizzo IS NULL)) ENABLE;
  ALTER TABLE "OOBD16"."GRUPPO" ADD CONSTRAINT "GRUPPOVIAGGIOVALIDO" CHECK (dataInizio<=dataFine) ENABLE;
  ALTER TABLE "OOBD16"."GRUPPO" ADD PRIMARY KEY ("IDGRUPPO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table NOTIFICA
--------------------------------------------------------

  ALTER TABLE "OOBD16"."NOTIFICA" MODIFY ("IDNOTIFICA" NOT NULL ENABLE);
  ALTER TABLE "OOBD16"."NOTIFICA" MODIFY ("DATA1" NOT NULL ENABLE);
  ALTER TABLE "OOBD16"."NOTIFICA" MODIFY ("DESCRIZIONE1" NOT NULL ENABLE);
  ALTER TABLE "OOBD16"."NOTIFICA" MODIFY ("IDDEBITO" NOT NULL ENABLE);
  ALTER TABLE "OOBD16"."NOTIFICA" ADD CONSTRAINT "NOTIFICADIRISPOSTAVALIDA" CHECK (data1<dataRisposta) ENABLE;
  ALTER TABLE "OOBD16"."NOTIFICA" ADD PRIMARY KEY ("IDNOTIFICA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PARTECIPAZIONEGRUPPO
--------------------------------------------------------

  ALTER TABLE "OOBD16"."PARTECIPAZIONEGRUPPO" MODIFY ("IDPARTECIPAZIONE" NOT NULL ENABLE);
  ALTER TABLE "OOBD16"."PARTECIPAZIONEGRUPPO" MODIFY ("DATAINVITO" NOT NULL ENABLE);
  ALTER TABLE "OOBD16"."PARTECIPAZIONEGRUPPO" MODIFY ("EMAILUTENTE" NOT NULL ENABLE);
  ALTER TABLE "OOBD16"."PARTECIPAZIONEGRUPPO" MODIFY ("IDGRUPPO" NOT NULL ENABLE);
  ALTER TABLE "OOBD16"."PARTECIPAZIONEGRUPPO" ADD CONSTRAINT "BOOL_STATOINVITO" CHECK (statoInvito IN(0,1)) ENABLE;
  ALTER TABLE "OOBD16"."PARTECIPAZIONEGRUPPO" ADD PRIMARY KEY ("IDPARTECIPAZIONE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "OOBD16"."PARTECIPAZIONEGRUPPO" ADD CONSTRAINT "PARTECIPAZIONEUNICA" UNIQUE ("EMAILUTENTE", "IDGRUPPO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DEBITO
--------------------------------------------------------

  ALTER TABLE "OOBD16"."DEBITO" ADD CONSTRAINT "FK_EMAILUTENTE3" FOREIGN KEY ("EMAILUTENTE")
	  REFERENCES "OOBD16"."UTENTE" ("EMAILISTITUZIONALE") ON DELETE SET NULL ENABLE;
  ALTER TABLE "OOBD16"."DEBITO" ADD CONSTRAINT "FK_IDSPESA" FOREIGN KEY ("IDSPESA")
	  REFERENCES "OOBD16"."SPESA" ("IDSPESA") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GRUPPO
--------------------------------------------------------

  ALTER TABLE "OOBD16"."GRUPPO" ADD CONSTRAINT "FK_EMAILPROPRIETARIO" FOREIGN KEY ("EMAILPROPRIETARIO")
	  REFERENCES "OOBD16"."UTENTE" ("EMAILISTITUZIONALE") ON DELETE SET NULL ENABLE;
  ALTER TABLE "OOBD16"."GRUPPO" ADD CONSTRAINT "FK_INDIRIZZO" FOREIGN KEY ("INDIRIZZO")
	  REFERENCES "OOBD16"."INDIRIZZO" ("IDINDIRIZZO") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NOTIFICA
--------------------------------------------------------

  ALTER TABLE "OOBD16"."NOTIFICA" ADD CONSTRAINT "FK_IDDEBITO" FOREIGN KEY ("IDDEBITO")
	  REFERENCES "OOBD16"."DEBITO" ("IDDEBITO") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PARTECIPAZIONEGRUPPO
--------------------------------------------------------

  ALTER TABLE "OOBD16"."PARTECIPAZIONEGRUPPO" ADD CONSTRAINT "FK_EMAILUTENTE" FOREIGN KEY ("EMAILUTENTE")
	  REFERENCES "OOBD16"."UTENTE" ("EMAILISTITUZIONALE") ON DELETE CASCADE ENABLE;
  ALTER TABLE "OOBD16"."PARTECIPAZIONEGRUPPO" ADD CONSTRAINT "FK_IDGRUPPO" FOREIGN KEY ("IDGRUPPO")
	  REFERENCES "OOBD16"."GRUPPO" ("IDGRUPPO") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SCADENZA
--------------------------------------------------------

  ALTER TABLE "OOBD16"."SCADENZA" ADD CONSTRAINT "FK_IDGRUPPO2" FOREIGN KEY ("IDGRUPPO")
	  REFERENCES "OOBD16"."GRUPPO" ("IDGRUPPO") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SPESA
--------------------------------------------------------

  ALTER TABLE "OOBD16"."SPESA" ADD CONSTRAINT "FK_EMAILUTENTE2" FOREIGN KEY ("EMAILUTENTE")
	  REFERENCES "OOBD16"."UTENTE" ("EMAILISTITUZIONALE") ON DELETE SET NULL ENABLE;
  ALTER TABLE "OOBD16"."SPESA" ADD CONSTRAINT "FK_IDGRUPPO3" FOREIGN KEY ("IDGRUPPO")
	  REFERENCES "OOBD16"."GRUPPO" ("IDGRUPPO") ON DELETE CASCADE ENABLE;
  ALTER TABLE "OOBD16"."SPESA" ADD CONSTRAINT "FK_VALUTA" FOREIGN KEY ("VALUTA")
	  REFERENCES "OOBD16"."VALUTA" ("NOME") ON DELETE SET NULL ENABLE;
